/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type S3BlobStoreApiBucketConfiguration struct {
	Bucket *S3BlobStoreApiBucket `json:"bucket"`
	Encryption *S3BlobStoreApiEncryption `json:"encryption,omitempty"`
	BucketSecurity *S3BlobStoreApiBucketSecurity `json:"bucketSecurity,omitempty"`
	AdvancedBucketConnection *S3BlobStoreApiAdvancedBucketConnection `json:"advancedBucketConnection,omitempty"`
}
