/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type DockerProxyAttributes struct {
	// Type of Docker Index
	IndexType string `json:"indexType,omitempty"`
	// Url of Docker Index to use
	IndexUrl string `json:"indexUrl,omitempty"`
}
