/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type ApiUser struct {
	// The userid which is required for login. This value cannot be changed.
	UserId string `json:"userId,omitempty"`
	// The first name of the user.
	FirstName string `json:"firstName,omitempty"`
	// The last name of the user.
	LastName string `json:"lastName,omitempty"`
	// The email address associated with the user.
	EmailAddress string `json:"emailAddress,omitempty"`
	// The user source which is the origin of this user. This value cannot be changed.
	Source string `json:"source,omitempty"`
	// The user's status, e.g. active or disabled.
	Status string `json:"status"`
	// Indicates whether the user's properties could be modified by the Nexus Repository Manager. When false only roles are considered during update.
	ReadOnly bool `json:"readOnly,omitempty"`
	// The roles which the user has been assigned within Nexus.
	Roles []string `json:"roles,omitempty"`
	// The roles which the user has been assigned in an external source, e.g. LDAP group. These cannot be changed within the Nexus Repository Manager.
	ExternalRoles []string `json:"externalRoles,omitempty"`
}
