/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus
import (
	"time"
)

type ApiLicenseDetailsXo struct {
	ContactEmail string `json:"contactEmail,omitempty"`
	ContactCompany string `json:"contactCompany,omitempty"`
	ContactName string `json:"contactName,omitempty"`
	EffectiveDate time.Time `json:"effectiveDate,omitempty"`
	ExpirationDate time.Time `json:"expirationDate,omitempty"`
	LicenseType string `json:"licenseType,omitempty"`
	LicensedUsers string `json:"licensedUsers,omitempty"`
	Fingerprint string `json:"fingerprint,omitempty"`
	Features string `json:"features,omitempty"`
}
