/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type AnonymousAccessSettingsXo struct {
	// Whether or not Anonymous Access is enabled
	Enabled bool `json:"enabled,omitempty"`
	// The username of the anonymous account
	UserId string `json:"userId,omitempty"`
	// The name of the authentication realm for the anonymous account
	RealmName string `json:"realmName,omitempty"`
}
