/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type BlobStoreApiSoftQuota struct {
	// The type to use such as spaceRemainingQuota, or spaceUsedQuota
	Type_ string `json:"type,omitempty"`
	// The limit in MB.
	Limit int64 `json:"limit,omitempty"`
}
