/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus
import (
	"time"
)

type AssetXo struct {
	DownloadUrl string `json:"downloadUrl,omitempty"`
	Path string `json:"path,omitempty"`
	Id string `json:"id,omitempty"`
	Repository string `json:"repository,omitempty"`
	Format string `json:"format,omitempty"`
	Checksum map[string]interface{} `json:"checksum,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	LastModified time.Time `json:"lastModified,omitempty"`
}
