/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type ContentSelectorApiUpdateRequest struct {
	// An optional description of this content selector
	Description string `json:"description,omitempty"`
	// The expression used to identify content
	Expression string `json:"expression,omitempty"`
}
