/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus
import (
	"time"
)

type TaskXo struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
	CurrentState string `json:"currentState,omitempty"`
	LastRunResult string `json:"lastRunResult,omitempty"`
	NextRun time.Time `json:"nextRun,omitempty"`
	LastRun time.Time `json:"lastRun,omitempty"`
}
