/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type RoleXoResponse struct {
	// The id of the role.
	Id string `json:"id,omitempty"`
	// The user source which is the origin of this role.
	Source string `json:"source,omitempty"`
	// The name of the role.
	Name string `json:"name,omitempty"`
	// The description of this role.
	Description string `json:"description,omitempty"`
	// The list of privileges assigned to this role.
	Privileges []string `json:"privileges,omitempty"`
	// The list of roles assigned to this role.
	Roles []string `json:"roles,omitempty"`
}
