/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type ComponentXo struct {
	Id string `json:"id,omitempty"`
	Repository string `json:"repository,omitempty"`
	Format string `json:"format,omitempty"`
	Group string `json:"group,omitempty"`
	Name string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
	Assets []AssetXo `json:"assets,omitempty"`
}
