/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type ApiPrivilegeScriptRequest struct {
	// The name of the privilege.  This value cannot be changed.
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	// A collection of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	Actions []string `json:"actions,omitempty"`
	// The name of a script to give access to.
	ScriptName string `json:"scriptName,omitempty"`
}
