/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type S3BlobStoreApiModel struct {
	// The name of the S3 blob store.
	Name string `json:"name"`
	SoftQuota *BlobStoreApiSoftQuota `json:"softQuota,omitempty"`
	BucketConfiguration *S3BlobStoreApiBucketConfiguration `json:"bucketConfiguration"`
}
