/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type GroupDeployAttributes struct {
	// Member repositories' names
	MemberNames []string `json:"memberNames,omitempty"`
	// Pro-only: This field is for the Group Deployment feature available in NXRM Pro.
	WritableMember string `json:"writableMember,omitempty"`
}
