/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type ApiEmailConfiguration struct {
	Enabled bool `json:"enabled,omitempty"`
	Host string `json:"host,omitempty"`
	Port int32 `json:"port"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	FromAddress string `json:"fromAddress,omitempty"`
	// A prefix to add to all email subjects to aid in identifying automated emails
	SubjectPrefix string `json:"subjectPrefix,omitempty"`
	// Enable STARTTLS Support for Insecure Connections
	StartTlsEnabled bool `json:"startTlsEnabled,omitempty"`
	// Require STARTTLS Support
	StartTlsRequired bool `json:"startTlsRequired,omitempty"`
	// Enable SSL/TLS Encryption upon Connection
	SslOnConnectEnabled bool `json:"sslOnConnectEnabled,omitempty"`
	// Verify the server certificate when using TLS or SSL
	SslServerIdentityCheckEnabled bool `json:"sslServerIdentityCheckEnabled,omitempty"`
	// Use the Nexus Repository Manager's certificate truststore
	NexusTrustStoreEnabled bool `json:"nexusTrustStoreEnabled,omitempty"`
}
