/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type UploadFieldDefinitionXo struct {
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	Optional bool `json:"optional,omitempty"`
	Group string `json:"group,omitempty"`
}
