/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type NugetAttributes struct {
	// How long to cache query results from the proxied repository (in seconds)
	QueryCacheItemMaxAge int32 `json:"queryCacheItemMaxAge,omitempty"`
	// Nuget protocol version
	NugetVersion string `json:"nugetVersion,omitempty"`
}
