/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type S3BlobStoreApiEncryption struct {
	// The type of S3 server side encryption to use.
	EncryptionType string `json:"encryptionType,omitempty"`
	// The encryption key.
	EncryptionKey string `json:"encryptionKey,omitempty"`
}
