/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type MavenAttributes struct {
	// What type of artifacts does this repository store?
	VersionPolicy string `json:"versionPolicy,omitempty"`
	// Validate that all paths are maven artifact or metadata paths
	LayoutPolicy string `json:"layoutPolicy,omitempty"`
}
