/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type CleanupPolicyAttributes struct {
	// Components that match any of the applied policies will be deleted
	PolicyNames []string `json:"policyNames,omitempty"`
}
