/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type IqConnectionXo struct {
	// Whether to use IQ Server
	Enabled bool `json:"enabled,omitempty"`
	// Show IQ Server link in Browse menu when server is enabled
	ShowLink bool `json:"showLink,omitempty"`
	// The address of your IQ Server
	Url string `json:"url,omitempty"`
	// Authentication method
	AuthenticationType string `json:"authenticationType"`
	// User with access to IQ Server
	Username string `json:"username,omitempty"`
	// Credentials for the IQ Server User
	Password string `json:"password,omitempty"`
	// Use certificates stored in the Nexus Repository Manager truststore to connect to IQ Server
	UseTrustStoreForUrl bool `json:"useTrustStoreForUrl,omitempty"`
	// Seconds to wait for activity before stopping and retrying the connection. Leave blank to use the globally defined HTTP timeout.
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
	// Additional properties to configure for IQ Server
	Properties string `json:"properties,omitempty"`
}
