/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus
import (
	"os"
)

type Body struct {
	// r Asset 
	RAsset **os.File `json:"r.asset,omitempty"`
	// r Asset  Package Path
	RAssetPathId string `json:"r.asset.pathId,omitempty"`
	// apt Asset 
	AptAsset **os.File `json:"apt.asset,omitempty"`
	// yum Directory
	YumDirectory string `json:"yum.directory,omitempty"`
	// yum Asset 
	YumAsset **os.File `json:"yum.asset,omitempty"`
	// yum Asset  Filename
	YumAssetFilename string `json:"yum.asset.filename,omitempty"`
	// docker Asset 
	DockerAsset **os.File `json:"docker.asset,omitempty"`
	// rubygems Asset 
	RubygemsAsset **os.File `json:"rubygems.asset,omitempty"`
	// nuget Asset 
	NugetAsset **os.File `json:"nuget.asset,omitempty"`
	// pypi Asset 
	PypiAsset **os.File `json:"pypi.asset,omitempty"`
	// helm Asset 
	HelmAsset **os.File `json:"helm.asset,omitempty"`
	// npm Asset 
	NpmAsset **os.File `json:"npm.asset,omitempty"`
	// raw Directory
	RawDirectory string `json:"raw.directory,omitempty"`
	// raw Asset 1
	RawAsset1 **os.File `json:"raw.asset1,omitempty"`
	// raw Asset 1 Filename
	RawAsset1Filename string `json:"raw.asset1.filename,omitempty"`
	// raw Asset 2
	RawAsset2 **os.File `json:"raw.asset2,omitempty"`
	// raw Asset 2 Filename
	RawAsset2Filename string `json:"raw.asset2.filename,omitempty"`
	// raw Asset 3
	RawAsset3 **os.File `json:"raw.asset3,omitempty"`
	// raw Asset 3 Filename
	RawAsset3Filename string `json:"raw.asset3.filename,omitempty"`
	// maven2 Group ID
	Maven2GroupId string `json:"maven2.groupId,omitempty"`
	// maven2 Artifact ID
	Maven2ArtifactId string `json:"maven2.artifactId,omitempty"`
	// maven2 Version
	Maven2Version string `json:"maven2.version,omitempty"`
	// maven2 Generate a POM file with these coordinates
	Maven2GeneratePom bool `json:"maven2.generate-pom,omitempty"`
	// maven2 Packaging
	Maven2Packaging string `json:"maven2.packaging,omitempty"`
	// maven2 Asset 1
	Maven2Asset1 **os.File `json:"maven2.asset1,omitempty"`
	// maven2 Asset 1 Classifier
	Maven2Asset1Classifier string `json:"maven2.asset1.classifier,omitempty"`
	// maven2 Asset 1 Extension
	Maven2Asset1Extension string `json:"maven2.asset1.extension,omitempty"`
	// maven2 Asset 2
	Maven2Asset2 **os.File `json:"maven2.asset2,omitempty"`
	// maven2 Asset 2 Classifier
	Maven2Asset2Classifier string `json:"maven2.asset2.classifier,omitempty"`
	// maven2 Asset 2 Extension
	Maven2Asset2Extension string `json:"maven2.asset2.extension,omitempty"`
	// maven2 Asset 3
	Maven2Asset3 **os.File `json:"maven2.asset3,omitempty"`
	// maven2 Asset 3 Classifier
	Maven2Asset3Classifier string `json:"maven2.asset3.classifier,omitempty"`
	// maven2 Asset 3 Extension
	Maven2Asset3Extension string `json:"maven2.asset3.extension,omitempty"`
}
