/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.29.0-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus

type S3BlobStoreApiBucketSecurity struct {
	// An IAM access key ID for granting access to the S3 bucket
	AccessKeyId string `json:"accessKeyId,omitempty"`
	// The secret access key associated with the specified IAM access key ID
	SecretAccessKey string `json:"secretAccessKey,omitempty"`
	// An IAM role to assume in order to access the S3 bucket
	Role string `json:"role,omitempty"`
	// An AWS STS session token associated with temporary security credentials which grant access to the S3 bucket
	SessionToken string `json:"sessionToken,omitempty"`
}
